const fs = require('fs');
let content = fs.readFileSync('src/data/flashcardsData.ts', 'utf8');

const englishCards = `
export const INITIAL_FLASHCARDS_EN: Flashcard[] = [
  {
    id: "fc-1",
    moduleId: 1,
    term: "Economic Moat",
    question: "What does Warren Buffett mean by the 'Economic Moat' metaphor?",
    answer: "A sustainable competitive shield that defends a company's profits and market share against imitators and competitors for decades.",
    analogy: "A wide, crocodile-filled water moat surrounding a medieval castle.",
    difficulty: "kolay",
    repetitions: 0,
    intervalDays: 1,
    easeFactor: 2.5,
    nextReviewDate: new Date().toISOString(),
  },
  {
    id: "fc-2",
    moduleId: 1,
    term: "ROIC vs WACC Spread",
    question: "What must be the relationship between ROIC and WACC for a company to create true shareholder value?",
    answer: "ROIC (Return on Invested Capital) must exceed WACC (Cost of Capital). A positive spread proves the firm creates net incremental economic wealth for shareholders.",
    analogy: "Earning 15% on a business when your cost of funds is 8% (+7% net compounding spread).",
    difficulty: "orta",
    repetitions: 0,
    intervalDays: 1,
    easeFactor: 2.5,
    nextReviewDate: new Date().toISOString(),
  },
  {
    id: "fc-3",
    moduleId: 1,
    term: "Mean Reversion",
    question: "What is the law of 'Mean Reversion' in corporate returns?",
    answer: "The tendency for companies with abnormally high ROIC to see returns decay toward market averages within 5-10 years due to intense competitive onslaught.",
    analogy: "Profits of a booming cafe eroding quickly as 5 new cafes open next door.",
    difficulty: "orta",
    repetitions: 0,
    intervalDays: 1,
    easeFactor: 2.5,
    nextReviewDate: new Date().toISOString(),
  },
  {
    id: "fc-4",
    moduleId: 2,
    term: "Dickinson Cash Flow Life Cycle",
    question: "What are the cash flow signs of a company in the 'Maturity' stage according to Victoria Dickinson?",
    answer: "Operating Cash Flow (+), Investing Cash Flow (-), Financing Cash Flow (-). The company funds investments from internal cash and returns surplus to shareholders.",
    analogy: "A high-earning professional paying down their mortgage and building retirement savings.",
    difficulty: "zor",
    repetitions: 0,
    intervalDays: 1,
    easeFactor: 2.5,
    nextReviewDate: new Date().toISOString(),
  },
  {
    id: "fc-5",
    moduleId: 3,
    term: "The Value Stick",
    question: "How is 'Consumer Surplus' calculated on the Value Stick?",
    answer: "Consumer Surplus = WTP (Willingness to Pay) - Price. It's the difference between the maximum value in the customer's mind and the actual price paid.",
    analogy: "Getting $40 of happiness when paying $60 for a coffee you value at $100.",
    difficulty: "kolay",
    repetitions: 0,
    intervalDays: 1,
    easeFactor: 2.5,
    nextReviewDate: new Date().toISOString(),
  },
  {
    id: "fc-6",
    moduleId: 3,
    term: "Willingness to Sell (WTS)",
    question: "How do companies lower the WTS (Willingness to Sell) of suppliers and employees?",
    answer: "By sharing sales data to reduce supplier inventory costs, or by offering employees autonomy, mastery, and a great culture.",
    analogy: "Walmart sharing data with Procter & Gamble to run factories more efficiently.",
    difficulty: "zor",
    repetitions: 0,
    intervalDays: 1,
    easeFactor: 2.5,
    nextReviewDate: new Date().toISOString(),
  },
  {
    id: "fc-7",
    moduleId: 4,
    term: "Profit Pool",
    question: "How do you understand the economic profit size of an industry segment in a Profit Pool analysis?",
    answer: "The Area of the Box (Width [Share of Invested Capital] × Height [ROIC - WACC]).",
    analogy: "Huge profits coming from the lobby popcorn rather than the movie ticket box office.",
    difficulty: "orta",
    repetitions: 0,
    intervalDays: 1,
    easeFactor: 2.5,
    nextReviewDate: new Date().toISOString(),
  },
  {
    id: "fc-8",
    moduleId: 4,
    term: "Market Share Volatility (2% Rule)",
    question: "According to Bruce Greenwald, what should be the 5-year absolute market share change for an industry to be considered 'stable'?",
    answer: "An annual average of 2% or lower. Changes greater than 2% indicate severe volatility and weak moats in the industry.",
    analogy: "Everyone's chair remaining stable.",
    difficulty: "orta",
    repetitions: 0,
    intervalDays: 1,
    easeFactor: 2.5,
    nextReviewDate: new Date().toISOString(),
  },
  {
    id: "fc-9",
    moduleId: 5,
    term: "Wright's Law (Learning Curve)",
    question: "What does Wright's Law say about production costs?",
    answer: "For every cumulative doubling of production volume, unit production and labor costs decrease by approximately 20%.",
    analogy: "Baking a cake much faster and flawlessly on your 100th try compared to your first.",
    difficulty: "kolay",
    repetitions: 0,
    intervalDays: 1,
    easeFactor: 2.5,
    nextReviewDate: new Date().toISOString(),
  },
  {
    id: "fc-10",
    moduleId: 5,
    term: "Minimum Efficient Scale (MES)",
    question: "What is Minimum Efficient Scale (MES)?",
    answer: "The minimum market share or output level a company must produce to achieve the lowest possible unit cost.",
    analogy: "A chip factory having to produce at least 10 million chips a year to be profitable.",
    difficulty: "orta",
    repetitions: 0,
    intervalDays: 1,
    easeFactor: 2.5,
    nextReviewDate: new Date().toISOString(),
  },
  {
    id: "fc-11",
    moduleId: 6,
    term: "Disruptive Innovation",
    question: "According to Clayton Christensen, why does Disruptive Innovation initially not attract existing giants?",
    answer: "Because initially, they are lower-quality, lower-margin products in a sub-segment that the market leader's wealthiest customers don't care about.",
    analogy: "Mini-mills starting to produce rebar, which giant steelmakers abandoned because of low margins.",
    difficulty: "orta",
    repetitions: 0,
    intervalDays: 1,
    easeFactor: 2.5,
    nextReviewDate: new Date().toISOString(),
  },
  {
    id: "fc-12",
    moduleId: 6,
    term: "Market Overshooting",
    question: "What does 'overshooting' a market mean?",
    answer: "When leaders add more features to a product than the customer demands or is willing to pay for, making the product too expensive.",
    analogy: "Trying to sell a $100,000 supercomputer to someone who just wants to read emails.",
    difficulty: "orta",
    repetitions: 0,
    intervalDays: 1,
    easeFactor: 2.5,
    nextReviewDate: new Date().toISOString(),
  },
  {
    id: "fc-13",
    moduleId: 7,
    term: "DuPont ROIC Breakdown",
    question: "What are the two core multiplying components of ROIC in a DuPont breakdown?",
    answer: "ROIC = (NOPAT / Revenue) × (Revenue / Invested Capital) -> NOPAT Margin × Capital Turnover.",
    analogy: "Luxury jewelers winning via huge margins vs. Costco winning via rapid inventory turns.",
    difficulty: "kolay",
    repetitions: 0,
    intervalDays: 1,
    easeFactor: 2.5,
    nextReviewDate: new Date().toISOString(),
  },
  {
    id: "fc-14",
    moduleId: 7,
    term: "Cash Conversion Cycle (CCC)",
    question: "What does a negative Cash Conversion Cycle (CCC) signify?",
    answer: "The company collects cash from customers before paying its suppliers, effectively funding growth with free, interest-free working capital float.",
    analogy: "Amazon collecting subscription and merchandise payments instantly while paying vendors on 60-day terms.",
    difficulty: "zor",
    repetitions: 0,
    intervalDays: 1,
    easeFactor: 2.5,
    nextReviewDate: new Date().toISOString(),
  },
  {
    id: "fc-15",
    moduleId: 8,
    term: "Tit-for-Tat",
    question: "Why is the 'Tit-for-Tat' strategy the most successful at preventing price wars in game theory?",
    answer: "It cooperates on the first turn, retaliates immediately if the rival cuts prices, and instantly forgives and returns to cooperation if the rival raises prices again.",
    analogy: "Start peacefully, respond instantly to attack, immediately forgive anyone who wants peace.",
    difficulty: "orta",
    repetitions: 0,
    intervalDays: 1,
    easeFactor: 2.5,
    nextReviewDate: new Date().toISOString(),
  },
  {
    id: "fc-16",
    moduleId: 8,
    term: "Colonel Blotto Game",
    question: "What does the Colonel Blotto game theory advise companies with limited resources?",
    answer: "Instead of fighting head-to-head with a giant rival on the main front, open new, niche fronts ignored by the rival and win the majority there.",
    analogy: "Breeze Airways flying between small cities instead of major airports where giants battle.",
    difficulty: "zor",
    repetitions: 0,
    intervalDays: 1,
    easeFactor: 2.5,
    nextReviewDate: new Date().toISOString(),
  },
  {
    id: "fc-17",
    moduleId: 8,
    term: "Tiffany vs Costco Diamond Test",
    question: "What does the fact that a Tiffany diamond can sell for $10,000 more than a Costco diamond prove?",
    answer: "That the brand is not just a logo; it's a value mechanism that increases WTP (Willingness to Pay) through status, trust, and reducing search costs.",
    analogy: "The prestige difference created by gifting a blue Tiffany box.",
    difficulty: "kolay",
    repetitions: 0,
    intervalDays: 1,
    easeFactor: 2.5,
    nextReviewDate: new Date().toISOString(),
  },
  {
    id: "fc-18",
    moduleId: 8,
    term: "Linking & Leveraging",
    question: "Amazon creating AWS cloud computing is an example of which strategic concept?",
    answer: "Linking & Leveraging: Leveraging the capability developed for its own e-commerce infrastructure into the adjacent cloud computing market, turning it into a massive profit center.",
    analogy: "Selling wholesale bread baked in your own cafe's oven during idle hours.",
    difficulty: "orta",
    repetitions: 0,
    intervalDays: 1,
    easeFactor: 2.5,
    nextReviewDate: new Date().toISOString(),
  }
];
`;

content += englishCards;
fs.writeFileSync('src/data/flashcardsData.ts', content, 'utf8');
